# coding: utf-8

from __future__ import absolute_import

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ModelBreak(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        start_timestamp: int = None,
        end_timestamp: int = None,
        position_lat: float = None,
        position_long: float = None,
    ):
        """ModelBreak - a model defined in Swagger

        :param start_timestamp: The start_timestamp of this ModelBreak.
        :type start_timestamp: int
        :param end_timestamp: The end_timestamp of this ModelBreak.
        :type end_timestamp: int
        :param position_lat: The position_lat of this ModelBreak.
        :type position_lat: float
        :param position_long: The position_long of this ModelBreak.
        :type position_long: float
        """
        self.swagger_types = {
            "start_timestamp": int,
            "end_timestamp": int,
            "position_lat": float,
            "position_long": float,
        }

        self.attribute_map = {
            "start_timestamp": "startTimestamp",
            "end_timestamp": "endTimestamp",
            "position_lat": "positionLat",
            "position_long": "positionLong",
        }

        self._start_timestamp = start_timestamp
        self._end_timestamp = end_timestamp
        self._position_lat = position_lat
        self._position_long = position_long

    @classmethod
    def from_dict(cls, dikt) -> "ModelBreak":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Break of this ModelBreak.
        :rtype: ModelBreak
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_timestamp(self) -> int:
        """Gets the start_timestamp of this ModelBreak.


        :return: The start_timestamp of this ModelBreak.
        :rtype: int
        """
        return self._start_timestamp

    @start_timestamp.setter
    def start_timestamp(self, start_timestamp: int):
        """Sets the start_timestamp of this ModelBreak.


        :param start_timestamp: The start_timestamp of this ModelBreak.
        :type start_timestamp: int
        """

        self._start_timestamp = start_timestamp

    @property
    def end_timestamp(self) -> int:
        """Gets the end_timestamp of this ModelBreak.


        :return: The end_timestamp of this ModelBreak.
        :rtype: int
        """
        return self._end_timestamp

    @end_timestamp.setter
    def end_timestamp(self, end_timestamp: int):
        """Sets the end_timestamp of this ModelBreak.


        :param end_timestamp: The end_timestamp of this ModelBreak.
        :type end_timestamp: int
        """

        self._end_timestamp = end_timestamp

    @property
    def position_lat(self) -> float:
        """Gets the position_lat of this ModelBreak.


        :return: The position_lat of this ModelBreak.
        :rtype: float
        """
        return self._position_lat

    @position_lat.setter
    def position_lat(self, position_lat: float):
        """Sets the position_lat of this ModelBreak.


        :param position_lat: The position_lat of this ModelBreak.
        :type position_lat: float
        """

        self._position_lat = position_lat

    @property
    def position_long(self) -> float:
        """Gets the position_long of this ModelBreak.


        :return: The position_long of this ModelBreak.
        :rtype: float
        """
        return self._position_long

    @position_long.setter
    def position_long(self, position_long: float):
        """Sets the position_long of this ModelBreak.


        :param position_long: The position_long of this ModelBreak.
        :type position_long: float
        """

        self._position_long = position_long
