# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VehiclePushDataPoint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, timestamp: int=None, odometer: int=None, fuel_level: int=None, position_lat: float=None, position_long: float=None):
        """VehiclePushDataPoint - a model defined in Swagger

        :param timestamp: The timestamp of this VehiclePushDataPoint.
        :type timestamp: int
        :param odometer: The odometer of this VehiclePushDataPoint.
        :type odometer: int
        :param fuel_level: The fuel_level of this VehiclePushDataPoint.
        :type fuel_level: int
        :param position_lat: The position_lat of this VehiclePushDataPoint.
        :type position_lat: float
        :param position_long: The position_long of this VehiclePushDataPoint.
        :type position_long: float
        """
        self.swagger_types = {
            'timestamp': int,
            'odometer': int,
            'fuel_level': int,
            'position_lat': float,
            'position_long': float
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'odometer': 'odometer',
            'fuel_level': 'fuelLevel',
            'position_lat': 'positionLat',
            'position_long': 'positionLong'
        }

        self._timestamp = timestamp
        self._odometer = odometer
        self._fuel_level = fuel_level
        self._position_lat = position_lat
        self._position_long = position_long

    @classmethod
    def from_dict(cls, dikt) -> 'VehiclePushDataPoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VehiclePushDataPoint of this VehiclePushDataPoint.
        :rtype: VehiclePushDataPoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> int:
        """Gets the timestamp of this VehiclePushDataPoint.

        unix timestamp

        :return: The timestamp of this VehiclePushDataPoint.
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: int):
        """Sets the timestamp of this VehiclePushDataPoint.

        unix timestamp

        :param timestamp: The timestamp of this VehiclePushDataPoint.
        :type timestamp: int
        """

        self._timestamp = timestamp

    @property
    def odometer(self) -> int:
        """Gets the odometer of this VehiclePushDataPoint.

        odometer value for a given time

        :return: The odometer of this VehiclePushDataPoint.
        :rtype: int
        """
        return self._odometer

    @odometer.setter
    def odometer(self, odometer: int):
        """Sets the odometer of this VehiclePushDataPoint.

        odometer value for a given time

        :param odometer: The odometer of this VehiclePushDataPoint.
        :type odometer: int
        """

        self._odometer = odometer

    @property
    def fuel_level(self) -> int:
        """Gets the fuel_level of this VehiclePushDataPoint.

        fuel level for a given time in percent

        :return: The fuel_level of this VehiclePushDataPoint.
        :rtype: int
        """
        return self._fuel_level

    @fuel_level.setter
    def fuel_level(self, fuel_level: int):
        """Sets the fuel_level of this VehiclePushDataPoint.

        fuel level for a given time in percent

        :param fuel_level: The fuel_level of this VehiclePushDataPoint.
        :type fuel_level: int
        """
        if fuel_level is not None and fuel_level > 100:
            raise ValueError("Invalid value for `fuel_level`, must be a value less than or equal to `100`")
        if fuel_level is not None and fuel_level < 0:
            raise ValueError("Invalid value for `fuel_level`, must be a value greater than or equal to `0`")

        self._fuel_level = fuel_level

    @property
    def position_lat(self) -> float:
        """Gets the position_lat of this VehiclePushDataPoint.

        latitude position for a given time

        :return: The position_lat of this VehiclePushDataPoint.
        :rtype: float
        """
        return self._position_lat

    @position_lat.setter
    def position_lat(self, position_lat: float):
        """Sets the position_lat of this VehiclePushDataPoint.

        latitude position for a given time

        :param position_lat: The position_lat of this VehiclePushDataPoint.
        :type position_lat: float
        """

        self._position_lat = position_lat

    @property
    def position_long(self) -> float:
        """Gets the position_long of this VehiclePushDataPoint.

        longitude position for a given time

        :return: The position_long of this VehiclePushDataPoint.
        :rtype: float
        """
        return self._position_long

    @position_long.setter
    def position_long(self, position_long: float):
        """Sets the position_long of this VehiclePushDataPoint.

        longitude position for a given time

        :param position_long: The position_long of this VehiclePushDataPoint.
        :type position_long: float
        """

        self._position_long = position_long
