# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.model_break import ModelBreak


class VehiclePushAnalysis(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, vin: str=None, departure: str=None, destination: str=None, refuel_stops: List[ModelBreak]=None, consumption: float=None, breaks: List[ModelBreak]=None):
        """VehiclePushAnalysis - a model defined in Swagger

        :param vin: The vin of this VehiclePushAnalysis.
        :type vin: str
        :param departure: The departure of this VehiclePushAnalysis.
        :type departure: str
        :param destination: The destination of this VehiclePushAnalysis.
        :type destination: str
        :param refuel_stops: The refuel_stops of this VehiclePushAnalysis.
        :type refuel_stops: List[ModelBreak]
        :param consumption: The consumption of this VehiclePushAnalysis.
        :type consumption: float
        :param breaks: The breaks of this VehiclePushAnalysis.
        :type breaks: List[ModelBreak]
        """
        self.swagger_types = {
            'vin': str,
            'departure': str,
            'destination': str,
            'refuel_stops': List[ModelBreak],
            'consumption': float,
            'breaks': List[ModelBreak]
        }

        self.attribute_map = {
            'vin': 'vin',
            'departure': 'departure',
            'destination': 'destination',
            'refuel_stops': 'refuelStops',
            'consumption': 'consumption',
            'breaks': 'breaks'
        }

        self._vin = vin
        self._departure = departure
        self._destination = destination
        self._refuel_stops = refuel_stops
        self._consumption = consumption
        self._breaks = breaks

    @classmethod
    def from_dict(cls, dikt) -> 'VehiclePushAnalysis':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VehiclePushAnalysis of this VehiclePushAnalysis.
        :rtype: VehiclePushAnalysis
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vin(self) -> str:
        """Gets the vin of this VehiclePushAnalysis.

        vehicle identification number

        :return: The vin of this VehiclePushAnalysis.
        :rtype: str
        """
        return self._vin

    @vin.setter
    def vin(self, vin: str):
        """Sets the vin of this VehiclePushAnalysis.

        vehicle identification number

        :param vin: The vin of this VehiclePushAnalysis.
        :type vin: str
        """

        self._vin = vin

    @property
    def departure(self) -> str:
        """Gets the departure of this VehiclePushAnalysis.

        city/location where the trip started

        :return: The departure of this VehiclePushAnalysis.
        :rtype: str
        """
        return self._departure

    @departure.setter
    def departure(self, departure: str):
        """Sets the departure of this VehiclePushAnalysis.

        city/location where the trip started

        :param departure: The departure of this VehiclePushAnalysis.
        :type departure: str
        """

        self._departure = departure

    @property
    def destination(self) -> str:
        """Gets the destination of this VehiclePushAnalysis.

        city/location where the trip ended

        :return: The destination of this VehiclePushAnalysis.
        :rtype: str
        """
        return self._destination

    @destination.setter
    def destination(self, destination: str):
        """Sets the destination of this VehiclePushAnalysis.

        city/location where the trip ended

        :param destination: The destination of this VehiclePushAnalysis.
        :type destination: str
        """

        self._destination = destination

    @property
    def refuel_stops(self) -> List[ModelBreak]:
        """Gets the refuel_stops of this VehiclePushAnalysis.

        a list of all refuel stops during the trip

        :return: The refuel_stops of this VehiclePushAnalysis.
        :rtype: List[ModelBreak]
        """
        return self._refuel_stops

    @refuel_stops.setter
    def refuel_stops(self, refuel_stops: List[ModelBreak]):
        """Sets the refuel_stops of this VehiclePushAnalysis.

        a list of all refuel stops during the trip

        :param refuel_stops: The refuel_stops of this VehiclePushAnalysis.
        :type refuel_stops: List[ModelBreak]
        """

        self._refuel_stops = refuel_stops

    @property
    def consumption(self) -> float:
        """Gets the consumption of this VehiclePushAnalysis.

        the average consumption during the trip (l/100km)

        :return: The consumption of this VehiclePushAnalysis.
        :rtype: float
        """
        return self._consumption

    @consumption.setter
    def consumption(self, consumption: float):
        """Sets the consumption of this VehiclePushAnalysis.

        the average consumption during the trip (l/100km)

        :param consumption: The consumption of this VehiclePushAnalysis.
        :type consumption: float
        """

        self._consumption = consumption

    @property
    def breaks(self) -> List[ModelBreak]:
        """Gets the breaks of this VehiclePushAnalysis.

        a list of all breaks during the trip including the refuel stops

        :return: The breaks of this VehiclePushAnalysis.
        :rtype: List[ModelBreak]
        """
        return self._breaks

    @breaks.setter
    def breaks(self, breaks: List[ModelBreak]):
        """Sets the breaks of this VehiclePushAnalysis.

        a list of all breaks during the trip including the refuel stops

        :param breaks: The breaks of this VehiclePushAnalysis.
        :type breaks: List[ModelBreak]
        """

        self._breaks = breaks
