# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.vehicle_push_data_point import VehiclePushDataPoint


class VehiclePush(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, vin: str=None, break_threshold: int=None, gas_tank_size: int=None, data: List[VehiclePushDataPoint]=None):
        """VehiclePush - a model defined in Swagger

        :param vin: The vin of this VehiclePush.
        :type vin: str
        :param break_threshold: The break_threshold of this VehiclePush.
        :type break_threshold: int
        :param gas_tank_size: The gas_tank_size of this VehiclePush.
        :type gas_tank_size: int
        :param data: The data of this VehiclePush.
        :type data: List[VehiclePushDataPoint]
        """
        self.swagger_types = {
            'vin': str,
            'break_threshold': int,
            'gas_tank_size': int,
            'data': List[VehiclePushDataPoint]
        }

        self.attribute_map = {
            'vin': 'vin',
            'break_threshold': 'breakThreshold',
            'gas_tank_size': 'gasTankSize',
            'data': 'data'
        }

        self._vin = vin
        self._break_threshold = break_threshold
        self._gas_tank_size = gas_tank_size
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'VehiclePush':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VehiclePush of this VehiclePush.
        :rtype: VehiclePush
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vin(self) -> str:
        """Gets the vin of this VehiclePush.

        vehicle identification number

        :return: The vin of this VehiclePush.
        :rtype: str
        """
        return self._vin

    @vin.setter
    def vin(self, vin: str):
        """Sets the vin of this VehiclePush.

        vehicle identification number

        :param vin: The vin of this VehiclePush.
        :type vin: str
        """

        self._vin = vin

    @property
    def break_threshold(self) -> int:
        """Gets the break_threshold of this VehiclePush.

        threshold to calculate if a car just stopped or did a break

        :return: The break_threshold of this VehiclePush.
        :rtype: int
        """
        return self._break_threshold

    @break_threshold.setter
    def break_threshold(self, break_threshold: int):
        """Sets the break_threshold of this VehiclePush.

        threshold to calculate if a car just stopped or did a break

        :param break_threshold: The break_threshold of this VehiclePush.
        :type break_threshold: int
        """

        self._break_threshold = break_threshold

    @property
    def gas_tank_size(self) -> int:
        """Gets the gas_tank_size of this VehiclePush.

        the size of the gas tank in liter

        :return: The gas_tank_size of this VehiclePush.
        :rtype: int
        """
        return self._gas_tank_size

    @gas_tank_size.setter
    def gas_tank_size(self, gas_tank_size: int):
        """Sets the gas_tank_size of this VehiclePush.

        the size of the gas tank in liter

        :param gas_tank_size: The gas_tank_size of this VehiclePush.
        :type gas_tank_size: int
        """

        self._gas_tank_size = gas_tank_size

    @property
    def data(self) -> List[VehiclePushDataPoint]:
        """Gets the data of this VehiclePush.


        :return: The data of this VehiclePush.
        :rtype: List[VehiclePushDataPoint]
        """
        return self._data

    @data.setter
    def data(self, data: List[VehiclePushDataPoint]):
        """Sets the data of this VehiclePush.


        :param data: The data of this VehiclePush.
        :type data: List[VehiclePushDataPoint]
        """

        self._data = data
